"""
寶可夢中英日名稱對照表
"""

# 中文 -> 英文 對照
ZH_TO_EN = {
    # 第一世代 (001-151)
    "妙蛙種子": "Bulbasaur",
    "妙蛙草": "Ivysaur",
    "妙蛙花": "Venusaur",
    "小火龍": "Charmander",
    "火恐龍": "Charmeleon",
    "噴火龍": "Charizard",
    "傑尼龜": "Squirtle",
    "卡咪龜": "Wartortle",
    "水箭龜": "Blastoise",
    "綠毛蟲": "Caterpie",
    "鐵甲蛹": "Metapod",
    "巴大蝶": "Butterfree",
    "獨角蟲": "Weedle",
    "鐵殼蛹": "Kakuna",
    "大針蜂": "Beedrill",
    "波波": "Pidgey",
    "比比鳥": "Pidgeotto",
    "大比鳥": "Pidgeot",
    "小拉達": "Rattata",
    "拉達": "Raticate",
    "烈雀": "Spearow",
    "大嘴雀": "Fearow",
    "阿柏蛇": "Ekans",
    "阿柏怪": "Arbok",
    "皮卡丘": "Pikachu",
    "雷丘": "Raichu",
    "穿山鼠": "Sandshrew",
    "穿山王": "Sandslash",
    "尼多蘭": "Nidoran♀",
    "尼多娜": "Nidorina",
    "尼多后": "Nidoqueen",
    "尼多朗": "Nidoran♂",
    "尼多力諾": "Nidorino",
    "尼多王": "Nidoking",
    "皮皮": "Clefairy",
    "皮可西": "Clefable",
    "六尾": "Vulpix",
    "九尾": "Ninetales",
    "胖丁": "Jigglypuff",
    "胖可丁": "Wigglytuff",
    "超音蝠": "Zubat",
    "大嘴蝠": "Golbat",
    "走路草": "Oddish",
    "臭臭花": "Gloom",
    "霸王花": "Vileplume",
    "派拉斯": "Paras",
    "派拉斯特": "Parasect",
    "毛球": "Venonat",
    "摩魯蛾": "Venomoth",
    "地鼠": "Diglett",
    "三地鼠": "Dugtrio",
    "喵喵": "Meowth",
    "貓老大": "Persian",
    "可達鴨": "Psyduck",
    "哥達鴨": "Golduck",
    "猴怪": "Mankey",
    "火暴猴": "Primeape",
    "卡蒂狗": "Growlithe",
    "風速狗": "Arcanine",
    "蚊香蝌蚪": "Poliwag",
    "蚊香君": "Poliwhirl",
    "蚊香泳士": "Poliwrath",
    "凱西": "Abra",
    "勇基拉": "Kadabra",
    "胡地": "Alakazam",
    "腕力": "Machop",
    "豪力": "Machoke",
    "怪力": "Machamp",
    "喇叭芽": "Bellsprout",
    "口呆花": "Weepinbell",
    "大食花": "Victreebel",
    "瑪瑙水母": "Tentacool",
    "毒刺水母": "Tentacruel",
    "小拳石": "Geodude",
    "隆隆石": "Graveler",
    "隆隆岩": "Golem",
    "小火馬": "Ponyta",
    "烈焰馬": "Rapidash",
    "呆呆獸": "Slowpoke",
    "呆殼獸": "Slowbro",
    "小磁怪": "Magnemite",
    "三合一磁怪": "Magneton",
    "大蔥鴨": "Farfetch'd",
    "嘟嘟": "Doduo",
    "嘟嘟利": "Dodrio",
    "小海獅": "Seel",
    "白海獅": "Dewgong",
    "臭泥": "Grimer",
    "臭臭泥": "Muk",
    "大舌貝": "Shellder",
    "刺甲貝": "Cloyster",
    "鬼斯": "Gastly",
    "鬼斯通": "Haunter",
    "耿鬼": "Gengar",
    "大岩蛇": "Onix",
    "催眠貘": "Drowzee",
    "引夢貘人": "Hypno",
    "大鉗蟹": "Krabby",
    "巨鉗蟹": "Kingler",
    "霹靂電球": "Voltorb",
    "頑皮雷彈": "Electrode",
    "蛋蛋": "Exeggcute",
    "椰蛋樹": "Exeggutor",
    "卡拉卡拉": "Cubone",
    "嘎啦嘎啦": "Marowak",
    "飛腿郎": "Hitmonlee",
    "快拳郎": "Hitmonchan",
    "大舌頭": "Lickitung",
    "瓦斯彈": "Koffing",
    "雙彈瓦斯": "Weezing",
    "獨角犀牛": "Rhyhorn",
    "鑽角犀獸": "Rhydon",
    "吉利蛋": "Chansey",
    "蔓藤怪": "Tangela",
    "袋獸": "Kangaskhan",
    "墨海馬": "Horsea",
    "海刺龍": "Seadra",
    "角金魚": "Goldeen",
    "金魚王": "Seaking",
    "海星星": "Staryu",
    "寶石海星": "Starmie",
    "魔牆人偶": "Mr. Mime",
    "飛天螳螂": "Scyther",
    "迷唇姐": "Jynx",
    "電擊獸": "Electabuzz",
    "鴨嘴火獸": "Magmar",
    "凱羅斯": "Pinsir",
    "肯泰羅": "Tauros",
    "鯉魚王": "Magikarp",
    "暴鯉龍": "Gyarados",
    "拉普拉斯": "Lapras",
    "百變怪": "Ditto",
    "伊布": "Eevee",
    "水伊布": "Vaporeon",
    "雷伊布": "Jolteon",
    "火伊布": "Flareon",
    "多邊獸": "Porygon",
    "菊石獸": "Omanyte",
    "多刺菊石獸": "Omastar",
    "化石盔": "Kabuto",
    "鐮刀盔": "Kabutops",
    "化石翼龍": "Aerodactyl",
    "卡比獸": "Snorlax",
    "急凍鳥": "Articuno",
    "閃電鳥": "Zapdos",
    "火焰鳥": "Moltres",
    "迷你龍": "Dratini",
    "哈克龍": "Dragonair",
    "快龍": "Dragonite",
    "超夢": "Mewtwo",
    "夢幻": "Mew",

    # 第二世代 (152-251)
    "菊草葉": "Chikorita",
    "月桂葉": "Bayleef",
    "大竺葵": "Meganium",
    "火球鼠": "Cyndaquil",
    "火岩鼠": "Quilava",
    "火暴獸": "Typhlosion",
    "小鋸鱷": "Totodile",
    "藍鱷": "Croconaw",
    "大力鱷": "Feraligatr",
    "尾立": "Sentret",
    "大尾立": "Furret",
    "咕咕": "Hoothoot",
    "貓頭夜鷹": "Noctowl",
    "芭瓢蟲": "Ledyba",
    "安瓢蟲": "Ledian",
    "圓絲蛛": "Spinarak",
    "阿利多斯": "Ariados",
    "叉字蝠": "Crobat",
    "燈籠魚": "Chinchou",
    "電燈怪": "Lanturn",
    "皮丘": "Pichu",
    "皮寶寶": "Cleffa",
    "寶寶丁": "Igglybuff",
    "波克比": "Togepi",
    "波克基古": "Togetic",
    "天然雀": "Natu",
    "天然鳥": "Xatu",
    "咩利羊": "Mareep",
    "茸茸羊": "Flaaffy",
    "電龍": "Ampharos",
    "美麗花": "Bellossom",
    "瑪力露": "Marill",
    "瑪力露麗": "Azumarill",
    "樹才怪": "Sudowoodo",
    "牛蛙君": "Politoed",
    "毽子草": "Hoppip",
    "毽子花": "Skiploom",
    "毽子棉": "Jumpluff",
    "長尾怪手": "Aipom",
    "向日種子": "Sunkern",
    "向日花怪": "Sunflora",
    "蜻蜻蜓": "Yanma",
    "烏波": "Wooper",
    "沼王": "Quagsire",
    "太陽伊布": "Espeon",
    "月亮伊布": "Umbreon",
    "黑暗鴉": "Murkrow",
    "呆呆王": "Slowking",
    "夢妖": "Misdreavus",
    "未知圖騰": "Unown",
    "果然翁": "Wobbuffet",
    "麒麟奇": "Girafarig",
    "榛果球": "Pineco",
    "佛烈托斯": "Forretress",
    "土龍弟弟": "Dunsparce",
    "天蠍": "Gligar",
    "大鋼蛇": "Steelix",
    "布魯": "Snubbull",
    "布魯皇": "Granbull",
    "千針魚": "Qwilfish",
    "巨鉗螳螂": "Scizor",
    "壺壺": "Shuckle",
    "赫拉克羅斯": "Heracross",
    "狃拉": "Sneasel",
    "熊寶寶": "Teddiursa",
    "圈圈熊": "Ursaring",
    "熔岩蟲": "Slugma",
    "熔岩蝸牛": "Magcargo",
    "小山豬": "Swinub",
    "長毛豬": "Piloswine",
    "太陽珊瑚": "Corsola",
    "鐵砲魚": "Remoraid",
    "章魚桶": "Octillery",
    "信使鳥": "Delibird",
    "巨翅飛魚": "Mantine",
    "盔甲鳥": "Skarmory",
    "戴魯比": "Houndour",
    "黑魯加": "Houndoom",
    "刺龍王": "Kingdra",
    "小小象": "Phanpy",
    "頓甲": "Donphan",
    "多邊獸Ⅱ": "Porygon2",
    "驚角鹿": "Stantler",
    "圖圖犬": "Smeargle",
    "巴爾郎": "Tyrogue",
    "戰舞郎": "Hitmontop",
    "迷唇娃": "Smoochum",
    "電擊怪": "Elekid",
    "小鴨嘴龍": "Magby",
    "大奶罐": "Miltank",
    "幸福蛋": "Blissey",
    "雷公": "Raikou",
    "炎帝": "Entei",
    "水君": "Suicune",
    "幼基拉斯": "Larvitar",
    "沙基拉斯": "Pupitar",
    "班基拉斯": "Tyranitar",
    "洛奇亞": "Lugia",
    "鳳王": "Ho-Oh",
    "時拉比": "Celebi",

    # 第三世代 (252-386) 部分
    "木守宮": "Treecko",
    "森林蜥蜴": "Grovyle",
    "蜥蜴王": "Sceptile",
    "火稚雞": "Torchic",
    "力壯雞": "Combusken",
    "火焰雞": "Blaziken",
    "水躍魚": "Mudkip",
    "沼躍魚": "Marshtomp",
    "巨沼怪": "Swampert",
    "蓋歐卡": "Kyogre",
    "固拉多": "Groudon",
    "烈空坐": "Rayquaza",
    "拉帝亞斯": "Latias",
    "拉帝歐斯": "Latios",
    "代歐奇希斯": "Deoxys",
    "基拉祈": "Jirachi",

    # 第四世代 (387-493) 部分
    "草苗龜": "Turtwig",
    "樹林龜": "Grotle",
    "土台龜": "Torterra",
    "小火焰猴": "Chimchar",
    "猛火猴": "Monferno",
    "烈焰猴": "Infernape",
    "波加曼": "Piplup",
    "波皇子": "Prinplup",
    "帝王拿波": "Empoleon",
    "帕路奇亞": "Palkia",
    "帝牙盧卡": "Dialga",
    "騎拉帝納": "Giratina",
    "達克萊伊": "Darkrai",
    "謝米": "Shaymin",
    "阿爾宙斯": "Arceus",
    "瑪納霏": "Manaphy",
    "霏歐納": "Phione",
    "克雷色利亞": "Cresselia",
    "雷吉奇卡斯": "Regigigas",
    "席多藍恩": "Heatran",
    "葉伊布": "Leafeon",
    "冰伊布": "Glaceon",
    "路卡利歐": "Lucario",
    "利歐路": "Riolu",

    # 第五世代 (494-649) 部分
    "比克提尼": "Victini",
    "藤藤蛇": "Snivy",
    "青藤蛇": "Servine",
    "君主蛇": "Serperior",
    "暖暖豬": "Tepig",
    "炒炒豬": "Pignite",
    "炎武王": "Emboar",
    "水水獺": "Oshawott",
    "雙刃丸": "Dewott",
    "大劍鬼": "Samurott",
    "捷克羅姆": "Zekrom",
    "雷希拉姆": "Reshiram",
    "酋雷姆": "Kyurem",
    "蓋諾賽克特": "Genesect",
    "凱路迪歐": "Keldeo",
    "美洛耶塔": "Meloetta",

    # 第六世代 (650-721) 部分
    "哈力栗": "Chespin",
    "胖胖哈力": "Quilladin",
    "布里卡隆": "Chesnaught",
    "火狐狸": "Fennekin",
    "長尾火狐": "Braixen",
    "妖火紅狐": "Delphox",
    "呱呱泡蛙": "Froakie",
    "呱頭蛙": "Frogadier",
    "甲賀忍蛙": "Greninja",
    "哲爾尼亞斯": "Xerneas",
    "伊裴爾塔爾": "Yveltal",
    "基格爾德": "Zygarde",
    "蒂安希": "Diancie",
    "胡帕": "Hoopa",
    "波爾凱尼恩": "Volcanion",
    "仙子伊布": "Sylveon",

    # 第七世代 (722-809) 部分
    "木木梟": "Rowlet",
    "投羽梟": "Dartrix",
    "狙射樹梟": "Decidueye",
    "火斑喵": "Litten",
    "炎熱喵": "Torracat",
    "熾焰咆哮虎": "Incineroar",
    "球球海獅": "Popplio",
    "花漾海獅": "Brionne",
    "西獅海壬": "Primarina",
    "索爾迦雷歐": "Solgaleo",
    "露奈雅拉": "Lunala",
    "奈克洛茲瑪": "Necrozma",
    "瑪夏多": "Marshadow",
    "捷拉奧拉": "Zeraora",
    "美錄坦": "Meltan",
    "美錄梅塔": "Melmetal",

    # 第八世代 (810-905) 部分
    "敲音猴": "Grookey",
    "啪咚猴": "Thwackey",
    "轟擂金剛猩": "Rillaboom",
    "炎兔兒": "Scorbunny",
    "騰蹴小將": "Raboot",
    "閃焰王牌": "Cinderace",
    "淚眼蜥": "Sobble",
    "變澀蜥": "Drizzile",
    "千面避役": "Inteleon",
    "蒼響": "Zacian",
    "藏瑪然特": "Zamazenta",
    "無極汰那": "Eternatus",
    "武道熊師": "Urshifu",
    "蕾冠王": "Calyrex",

    # 第九世代 (906-) 部分
    "新葉喵": "Sprigatito",
    "呆火鱷": "Fuecoco",
    "潤水鴨": "Quaxly",
    "故勒頓": "Koraidon",
    "密勒頓": "Miraidon",

    # 常見別名
    "噴火龍VMAX": "Charizard VMAX",
    "皮卡丘VMAX": "Pikachu VMAX",
    "皮卡丘V": "Pikachu V",
    "噴火龍V": "Charizard V",
    "伊布VMAX": "Eevee VMAX",
    "超夢VMAX": "Mewtwo VMAX",
    "超夢V": "Mewtwo V",
    "快龍V": "Dragonite V",
    "噴火龍ex": "Charizard ex",
    "皮卡丘ex": "Pikachu ex",
    "超夢ex": "Mewtwo ex",
}

# 建立反向對照 (英文 -> 中文)
EN_TO_ZH = {v.lower(): k for k, v in ZH_TO_EN.items()}


def translate_to_english(query: str) -> str:
    """將中文名稱轉換為英文"""
    # 先檢查完整匹配
    if query in ZH_TO_EN:
        return ZH_TO_EN[query]

    # 檢查是否包含中文名稱
    for zh, en in ZH_TO_EN.items():
        if zh in query:
            return query.replace(zh, en)

    return query


def translate_to_chinese(name: str) -> str:
    """將英文名稱轉換為中文"""
    name_lower = name.lower()
    if name_lower in EN_TO_ZH:
        return EN_TO_ZH[name_lower]
    return None


# 日文 -> 英文 對照（常用熱門卡 + 高價值卡 PokemonGO/SV）
JP_TO_EN = {
    "ピカチュウ": "Pikachu",
    "ライチュウ": "Raichu",
    "ヒトカゲ": "Charmander",
    "リザード": "Charmeleon",
    "リザードン": "Charizard",
    "メガリザードン": "MEGA Charizard",
    "フシギダネ": "Bulbasaur",
    "フシギソウ": "Ivysaur",
    "フシギバナ": "Venusaur",
    "ゼニガメ": "Squirtle",
    "カメール": "Wartortle",
    "カメックス": "Blastoise",
    "イーブイ": "Eevee",
    "シャワーズ": "Vaporeon",
    "サンダース": "Jolteon",
    "ブースター": "Flareon",
    "エーフィ": "Espeon",
    "ブラッキー": "Umbreon",
    "リーフィア": "Leafeon",
    "グレイシア": "Glaceon",
    "ニンフィア": "Sylveon",
    "ミュウ": "Mew",
    "ミュウツー": "Mewtwo",
    "ルギア": "Lugia",
    "ホウオウ": "Ho-Oh",
    "セレビィ": "Celebi",
    "レックウザ": "Rayquaza",
    "ルカリオ": "Lucario",
    "ガブリアス": "Garchomp",
    "ゲンガー": "Gengar",
    "ヤドラン": "Slowbro",
    "カビゴン": "Snorlax",
    "ラプラス": "Lapras",
    "ニャース": "Meowth",
    "ペルシアン": "Persian",
    "ロコン": "Vulpix",
    "キュウコン": "Ninetales",
    "ヒノアラシ": "Cyndaquil",
    "マグマラシ": "Quilava",
    "バクフーン": "Typhlosion",
    "ワニノコ": "Totodile",
    "アリゲイツ": "Croconaw",
    "オーダイル": "Feraligatr",
    "チコリータ": "Chikorita",
    "ベイリーフ": "Bayleef",
    "メガニウム": "Meganium",
    "ヨーギラス": "Larvitar",
    "サナギラス": "Pupitar",
    "バンギラス": "Tyranitar",
    "ジラーチ": "Jirachi",
    "ディアルガ": "Dialga",
    "パルキア": "Palkia",
    "ギラティナ": "Giratina",
    "アルセウス": "Arceus",
    "ゼクロム": "Zekrom",
    "レシラム": "Reshiram",
    "キュレム": "Kyurem",
    "ゼルネアス": "Xerneas",
    "イベルタル": "Yveltal",
    "ジガルデ": "Zygarde",
    "ソルガレオ": "Solgaleo",
    "ルナアーラ": "Lunala",
    "ネクロズマ": "Necrozma",
    "ザシアン": "Zacian",
    "ザマゼンタ": "Zamazenta",
    "ムゲンダイナ": "Eternatus",
    "コライドン": "Koraidon",
    "ミライドン": "Miraidon",
    "テラパゴス": "Terapagos",
    "ガラル": "Galarian",
    "アローラ": "Alolan",
    "ヒスイ": "Hisuian",
    "パルデア": "Paldean",
    "ナンジャモ": "Iono",
    "アカマツ": "Atticus",
    "ボタン": "Penny",
    "メリッサ": "Marnie",
    "サナ": "Shauna",
    "セレナ": "Serena",
    "リーリエ": "Lillie",
    "アセロラ": "Acerola",
    "シロナ": "Cynthia",
    "カイ": "Kai",
    "ヒカリ": "Dawn",
    "サポート": "Supporter",
    "トレーナー": "Trainer",
    "エネルギー": "Energy",
    "マスターボール": "Master Ball",
    "スーパーボール": "Great Ball",
    "モンスターボール": "Poke Ball",
}


def translate_jp_to_english(query: str) -> str:
    """日文寶可夢/角色名稱轉英文（部分匹配）。"""
    if query in JP_TO_EN:
        return JP_TO_EN[query]
    for jp, en in JP_TO_EN.items():
        if jp in query:
            query = query.replace(jp, en)
    return query
